### ISSUE TITLE
[Pug] Saving in partial files

### ISSUE THREAD

**Issue by hahuutin** [emily0604/frontend-standard#2]
We have 2 files:
+ A main file where including a partial file
+ A partial file where I changed code and saving

Issue that browser still live reloading but changed not apply, I must come back main file and saving again then change applied.

I wanna that if saving in partial file, main file will be listening and apply changed.

**Comment by Serjo1987** [comment]
Hi, Hahuutin

Try this solution:

`npm install --save-dev gulp-watch gulp-pug gulp-watch-pug`
 
```
var watch = require('gulp-watch');
var pug = require('gulp-pug');
var gulp_watch_pug = require('gulp-watch-pug');
```

```
// = Build Pug
gulp.task('compile-pug', function (cb) {

  var jsonData = JSON.parse(fs.readFileSync('./tmp/data.json'));
  options.pug.locals = jsonData;

  return gulp.src(['*.pug', '!_*.pug'], {cwd: 'source'})
    .pipe(plumber(function(error){
        console.log("Error happend!", error.message);
        this.emit('end');
    }))
    .pipe($.changed('dest', {extension: '.html'}))
    .pipe($.pugInheritance({
      basedir: "source",
      skip: ['node_modules']
    }))

    **.pipe(watch('/**/*.pug'))
    .pipe(gulp_watch_pug('/**/*.pug', { delay: 100 }))
    .pipe(pug())**

    .pipe($.prettify(options.htmlPrettify))
    .pipe(plumber.stop())
    .pipe(gulp.dest(dest));
});
```

I don't sure that is the right solution, but unfortunately i can't to check it, cause i still don't have a local machine, i use now my notebook with window, so this solution is not workin on windows, error like: `The error is: Object.fs.readdirSync failed with EPERM`, so this linux folder doesn't have proper access permissions on windows.

Thanx ))

**Comment by emily0604** [comment]
It's resolved.
