### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by hahuutin** [emily0604/frontend-standard#4]
http://editorconfig.org/ will help us auto config for:
+ How line breaks is `lf` or `crlf`
+ Indent style and indent size
+ Trim trailing whitespace
+ Insert final new line

And all of config being consistency in team, this make sure all files that we create will follow convention of team.

__Require:__ Install [plugin for your editor/IDE](http://editorconfig.org/#download) to can read our `.editorconfig` file.

**Comment by Serjo1987** [comment]
Hi, I'm new worker (fron-tend dev) from Framgia, so this is a solution:

root = true

`[*]
end_of_line = lf
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
insert_final_newline = true`

**Comment by hahuutin** [comment]
Hi @Serjo1987 ,
That's right!
Thanks for your support!

Hi @emily0604 ,
I just create a pull request for that, please check it. Thanks!

**Comment by Serjo1987** [comment]
Hi, Hahuutin

Ok, thank you
