### ISSUE TITLE
package.json name cannot have spaces

### ISSUE THREAD

**Issue by hahuutin** [emily0604/frontend-standard#5]
When typing `npm install`, it has npm WARN that:
```
npm WARN Invalid name: "Frontend standard"
```
We should change the name to **Frontend-standard** or **FrontendStandard**

**Comment by Serjo1987** [comment]
Hi, Hahuutin

Yea, I have this problem to and i tyying to find the solution, as soon as i write the solution here

**Comment by Serjo1987** [comment]
I've got the solution! ))

Just rename in package.json: "Frontend standard" to "Frontend-standard"

**Comment by Serjo1987** [comment]
So about the name, i think there is no difference, cause the logic of the name is the same, like - Frontend standarts ))

**Comment by emily0604** [comment]
It's resolved.
