### ISSUE TITLE
Should we have a .gitignore file

### ISSUE THREAD

**Issue by hahuutin** [emily0604/frontend-standard#7]
I think it really necessary for some files, directories must be ignored in git repo such as **node_modules**, **\*.map**. How do you think?

**Comment by Serjo1987** [comment]
Hi, Hahuutin.

Yes, sure, cause it's not necessary to keep folders like node modules in repo and other, it's only good to keep package.json, and when we pull we can just: node update, so that good idea to create .gitignore

**Comment by emily0604** [comment]
It's resolved.
